In [ ]:
import pymysql
import csv
import os
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# csv 파일 읽기
def read_csv_file("파일이름"):
    data = []
    file_path = os.path.join("C:\\classes\\classes\\03_Web_crawling_rpa\\프로젝트\\DA35_2nd_3KIM_eulpl", 파일이름)
    with open(file_path, 'r', encoding = 'utf-8') as file:
        csv_reader = csv.reader(file)
        next(csv_reader)
        for row in csv_reader:
            data.append(row)
        return data
    
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# MySQL 데이터베이스 연결
conn = pymysql.connect(host="127.0.0.1",
                       port = 3306
                       user='pjt',
                       password='1111',
                       db='use_store',
                       charset='utf8mb4')
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 커서 객체 생성
cursor = conn.cursor()

# CSV 파일 읽기
data = read_csv_file('파일이름.csv')
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 테이블 생성
create_table_query = """
CREATE TABLE IF NOT EXISTS your_table_name (
    name VARCHAR(255),
    address VARCHAR(255),
    count INT,
    sympathy INT
);
"""

cursor.execute(create_table_query)
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 데이터 삽입
for row in data:
    name, address, count = row
    count = int(count)
    insert_query = "INSERT INTO your_table_name (name, address, count) VALUES (%s, %s, %s)"
    cursor.execute(insert_query, (name, address, count))

# 변경사항 커밋
conn.commit()

# 커서 및 연결 종료
cursor.close()
conn.close()
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
print("Data inserted successfully!")